name: Deploy from Jira Transition
on:
  repository_dispatch:
    types: [jira_transition]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Application
        run: |
          echo "Deploying for Issue ${{ github.event.client_payload.issue }}"
          if [ "$((RANDOM % 2))" -eq 0 ]; then
            echo "✅ Deployment Successful"
          else
            echo "❌ Deployment Failed"
            exit 1
          fi

      # 배포 성공 시 Jira 상태 업데이트
      - name: Update Jira Issue (Success)
        if: success()
        run: |
          curl -X POST \
          --url "https://jira.example.com/rest/api/2/issue/${{ github.event.client_payload.issue }}/transitions" \
          --header "Content-Type: application/json" \
          --user "${{ secrets.JIRA_USER }}:${{ secrets.JIRA_PASSWORD }}" \
          --data '{
            "transition": { "id": "121" },
            "update": {
              "comment": [
                {
                  "add": {
                    "body": "✅ Deployment successful for ${{ github.event.client_payload.issue }}."
                  }
                }
              ]
            }
          }'

      # 배포 실패 시 Jira 상태 업데이트
      - name: Update Jira Issue (Failure)
        if: failure()
        run: |
          curl -X POST \
          --url "https://jira.example.com/rest/api/2/issue/${{ github.event.client_payload.issue }}/transitions" \
          --header "Content-Type: application/json" \
          --user "${{ secrets.JIRA_USER }}:${{ secrets.JIRA_PASSWORD }}" \
          --data '{
            "transition": { "id": "111" },
            "update": {
              "comment": [
                {
                  "add": {
                    "body": "❌ Deployment failed for ${{ github.event.client_payload.issue }}."
                  }
                }
              ]
            }
          }'
