name: Deploy from Jira Transition
on:
  repository_dispatch:
    types: [jira_transition]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Application
        run: |
          echo "Deploying for Issue ${{ github.event.client_payload.issue }}"
          if [ "$((RANDOM % 2))" -eq 0 ]; then
            echo "✅ Deployment Successful"
          else
            echo "❌ Deployment Failed"
            exit 1
          fi

      - name: Update Jira Issue (Success)
        if: success()
        run: |
          curl -X PUT \
          --url "https://jira.example.com/rest/api/2/issue/${{ github.event.client_payload.issue }}" \
          --header "Content-Type: application/json" \
          --user "${{ secrets.JIRA_USER }}:${{ secrets.JIRA_PASSWORD }}" \
          --data '{
            "fields": {
              "status": { "name": "Deployed" }
            },
            "update": {
              "comment": [
                {
                  "add": {
                    "body": "✅ Deployment successful for ${{ github.event.client_payload.issue }}."
                  }
                }
              ]
            }
          }'
